### ISSUE TITLE
Can't install following instructions, Error: Cannot destructure property 'path' of 'flags' as it is undefined.

### ISSUE THREAD

**Issue by carcaussa** [newrelic/nr1-groundskeeper#125]
## Description
I am following the provided guide to install Groundskeeper, but when I execute:
nr1 nerdpack:clone -r https://github.com/newrelic/nr1-groundskeeper.git

I receive the error:
 »   Error: Cannot destructure property 'path' of 'flags' as it is undefined.
 »   Code: UNKNOWN

## Steps to Reproduce
Download the new relic client and configure the profile according to the New Relic developer center "Build on New Relic"
Try to install the app according to the documentation in https://github.com/newrelic/nr1-groundskeeper
When executing the first step of the clone:
nr1 nerdpack:clone -r https://github.com/newrelic/nr1-groundskeeper.git
the error happens
## Expected Behaviour
Clone of Git the repository

## Relevant Logs / Console output
 »   Error: Cannot destructure property 'path' of 'flags' as it is undefined.
 »   Code: UNKNOWN

## Your Environment

* NR1 CLI version used: @datanerd/nr1/2.83.5 win32-x64 node-v16.11.1
* Browser name and version: Version 120.0.6099.130 (Official Build) (64-bit)
* Operating System and version: Microsoft Windows [Version 10.0.22631.2861] and also happens in macOS 13.6.3

## Additional context
Windows
git version 2.42.0.windows.2
npm version 10.2.3

Mac
git version 2.39.3 (Apple Git-145)
npm version 9.6.4

**Comment by aso1124** [comment]
Hi @carcaussa - 

Unless you are planning to customize the code base, I would actually recommend you leverage the version of the app deployed to the global app catalog. To do so, log in to New Relic, go to `Add Data > Apps and Visualizations` and search for "Groundskeeper". Click the tile and subscribe the app to the your account(s).

If you were planning to play around with a custom version, could you try using just the vanilla git clone command instead? Overall you will need to run the following sets of commands:

```
git clone [repo-url]
cd nr1-groundskeeper
npm install
nr1 nerdpack:uuid -fg
```
That last command will create a new unique identifier for the app, which is necessary in order to deploy it.

**Comment by carcaussa** [comment]
Thank you I just did that and the app is showing and I can use it
